-- PHASE 1 (Real Share Link): schema only. No RPCs yet - those are a
-- separate migration (Phase 2), so a broken RPC never blocks this
-- table from existing, and this table's own correctness can be
-- reviewed on its own.
--
-- Design summary (see chat/commit message for the full rationale):
--   - Multi-use per token: many different users can join via the same
--     link. "Already used" is per-user (already a member), not
--     per-token - mirrors invite_member_by_email's `already_member`.
--   - At most one *logically active* link per list is an RPC-level
--     invariant (Phase 2's create_invite_link), not a DB constraint -
--     Postgres can't express a unique index over `expires_at > now()`
--     since that predicate isn't immutable. Old revoked/expired rows
--     are kept, not deleted, as an audit trail.
--   - All writes go through SECURITY DEFINER RPCs (Phase 2), never a
--     raw client insert/update/delete - same pattern as
--     invite_member_by_email. RLS here only ever grants SELECT.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.invite_links (
  id uuid primary key default gen_random_uuid(),
  list_id uuid not null references public.lists(id) on delete cascade,
  -- 24 random bytes, hex-encoded (48 chars) - URL-safe with no further
  -- encoding, 192 bits of entropy. Generated by create_invite_link in
  -- the next migration, not by a column default, so retry-on-collision
  -- logic (astronomically unlikely as it is) lives in one place.
  token text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  revoked_at timestamptz
);

create index if not exists idx_invite_links_list_id on public.invite_links(list_id);
-- token already has a unique index via the column constraint above -
-- that's also the index join_list_by_token's lookup uses.

alter table public.invite_links enable row level security;

-- Only the list owner can see a link's row (including its token) via
-- the client - matches "only owners may create or revoke links",
-- extended naturally to "only owners may even view one". Everyone
-- else (other members, anonymous visitors following a link) resolves
-- a token exclusively through join_list_by_token, a SECURITY DEFINER
-- RPC that bypasses RLS - they never need or get direct table access.
drop policy if exists "invite_links_select_owner_only" on public.invite_links;
create policy "invite_links_select_owner_only"
  on public.invite_links for select
  using (public.is_list_owner(list_id));

-- No insert/update/delete policies at all, and no such grants below -
-- every write happens inside a SECURITY DEFINER function (Phase 2),
-- which runs as the migration role and bypasses RLS entirely. Without
-- an insert/update/delete policy, RLS denies those operations outright
-- for any client-side role, so this is enough to make direct writes
-- impossible even before Phase 2 ships the functions.
grant usage on schema public to authenticated;
grant select on public.invite_links to authenticated;
